-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxp/6ib49lE7je8yj
hUwIiqLdVrHwWBblVYXFj8zd7zWgCgYIKoZIzj0DAQehRANCAAT05kc5SGU2zNzM
jHMHmfCJpM/EgtjvHrU0TuGjpXhHqOVftgC6MCnX0seY+zx8Ni0kTTxyk161uTaQ
vKHIPhZg
-----END PRIVATE KEY-----