export enum EmailPurpose {
  EMAIL_OTP = 'EMAIL_OTP',
  CLASS_BOOKING = 'CLASS_BOOKING',
  CLASS_REMINDER = 'CLASS_REMINDER',
  PAYMENT_CREDITED = 'PAYMENT_CREDITED',
  WALLET_TOP_UP = 'WALLET_TOP_UP',
  ADMIN_TEST = 'ADMIN_TEST',
  OTHER = 'OTHER',
}
